spring:
  application:
    name: POST-SERVICE
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect